- generic [ref=e2]:
  - generic [ref=e3]:
    - link "Skip to content" [ref=e4] [cursor=pointer]:
      - /url: "#start-of-content"
    - banner [ref=e6]:
      - heading "Navigation Menu" [level=2] [ref=e7]
      - generic [ref=e8]:
        - link "Homepage" [ref=e10] [cursor=pointer]:
          - /url: /
          - img [ref=e11]
        - generic [ref=e13]:
          - navigation "Global" [ref=e16]:
            - list [ref=e17]:
              - listitem [ref=e18]:
                - button "Platform" [ref=e20] [cursor=pointer]:
                  - text: Platform
                  - img [ref=e21]
              - listitem [ref=e23]:
                - button "Solutions" [ref=e25] [cursor=pointer]:
                  - text: Solutions
                  - img [ref=e26]
              - listitem [ref=e28]:
                - button "Resources" [ref=e30] [cursor=pointer]:
                  - text: Resources
                  - img [ref=e31]
              - listitem [ref=e33]:
                - button "Open Source" [ref=e35] [cursor=pointer]:
                  - text: Open Source
                  - img [ref=e36]
              - listitem [ref=e38]:
                - button "Enterprise" [ref=e40] [cursor=pointer]:
                  - text: Enterprise
                  - img [ref=e41]
              - listitem [ref=e43]:
                - link "Pricing" [ref=e44] [cursor=pointer]:
                  - /url: https://github.com/pricing
                  - generic [ref=e45]: Pricing
          - generic [ref=e46]:
            - button "Search or jump to…" [ref=e49] [cursor=pointer]:
              - img [ref=e51]
            - link "Sign in" [ref=e54] [cursor=pointer]:
              - /url: /login?return_to=https%3A%2F%2Fgithub.com%2Fxujian519%2Fyunpat-agent%2Factions
            - link "Sign up" [ref=e55] [cursor=pointer]:
              - /url: /signup?ref_cta=Sign+up&ref_loc=header+logged+out&ref_page=%2F%3Cuser-name%3E%2F%3Crepo-name%3E%2Factions%2Findex&source=header-repo&source_repo=xujian519%2Fyunpat-agent
            - button "Appearance settings" [ref=e58] [cursor=pointer]:
              - img
  - main [ref=e62]:
    - generic [ref=e63]:
      - generic [ref=e64]:
        - generic [ref=e66]:
          - img [ref=e67]
          - link "xujian519" [ref=e70] [cursor=pointer]:
            - /url: /xujian519
          - generic [ref=e71]: /
          - strong [ref=e72]:
            - link "yunpat-agent" [ref=e73] [cursor=pointer]:
              - /url: /xujian519/yunpat-agent
          - generic [ref=e74]: Public
        - generic [ref=e75]:
          - list:
            - listitem [ref=e76]:
              - link "You must be signed in to change notification settings" [ref=e77] [cursor=pointer]:
                - /url: /login?return_to=%2Fxujian519%2Fyunpat-agent
                - img [ref=e78]
                - text: Notifications
            - listitem [ref=e80]:
              - link "Fork 0" [ref=e81] [cursor=pointer]:
                - /url: /login?return_to=%2Fxujian519%2Fyunpat-agent
                - img [ref=e82]
                - text: Fork
                - generic "0" [ref=e84]
            - listitem [ref=e85]:
              - link "You must be signed in to star a repository" [ref=e87] [cursor=pointer]:
                - /url: /login?return_to=%2Fxujian519%2Fyunpat-agent
                - img [ref=e88]
                - text: Star
                - generic "0 users starred this repository" [ref=e90]: "0"
      - navigation "Repository" [ref=e91]:
        - list [ref=e92]:
          - listitem [ref=e93]:
            - link "Code" [ref=e94] [cursor=pointer]:
              - /url: /xujian519/yunpat-agent
              - img [ref=e95]
              - generic [ref=e97]: Code
          - listitem [ref=e98]:
            - link "Issues" [ref=e99] [cursor=pointer]:
              - /url: /xujian519/yunpat-agent/issues
              - img [ref=e100]
              - generic [ref=e103]: Issues
          - listitem [ref=e104]:
            - link "Pull requests" [ref=e105] [cursor=pointer]:
              - /url: /xujian519/yunpat-agent/pulls
              - img [ref=e106]
              - generic [ref=e108]: Pull requests
          - listitem [ref=e109]:
            - link "Actions" [ref=e110] [cursor=pointer]:
              - /url: /xujian519/yunpat-agent/actions
              - img [ref=e111]
              - generic [ref=e113]: Actions
          - listitem [ref=e114]:
            - link "Projects" [ref=e115] [cursor=pointer]:
              - /url: /xujian519/yunpat-agent/projects
              - img [ref=e116]
              - generic [ref=e118]: Projects
          - listitem [ref=e119]:
            - link "Security and quality" [ref=e120] [cursor=pointer]:
              - /url: /xujian519/yunpat-agent/security
              - img [ref=e121]
              - generic [ref=e123]: Security and quality
          - listitem [ref=e124]:
            - link "Insights" [ref=e125] [cursor=pointer]:
              - /url: /xujian519/yunpat-agent/pulse
              - img [ref=e126]
              - generic [ref=e128]: Insights
    - generic [ref=e130]:
      - 'heading "Actions: xujian519/yunpat-agent" [level=1] [ref=e131]'
      - generic [ref=e134]:
        - generic [ref=e135]:
          - heading "Actions" [level=2] [ref=e137]
          - navigation "Actions Workflows" [ref=e141]:
            - list [ref=e143]:
              - listitem [ref=e144]:
                - link "All workflows" [ref=e145] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/actions
                  - generic [ref=e146]: All workflows
              - listitem [ref=e147]
              - listitem [ref=e148]:
                - list "Workflows" [ref=e152]:
                  - listitem [ref=e153]:
                    - link "CI" [ref=e154] [cursor=pointer]:
                      - /url: /xujian519/yunpat-agent/actions/workflows/ci.yml
                      - generic [ref=e155]: CI
              - listitem [ref=e156]
              - listitem [ref=e157]:
                - generic [ref=e160]:
                  - heading "Management" [level=3] [ref=e162]
                  - list "Management" [ref=e163]:
                    - listitem [ref=e164]:
                      - link "Caches" [ref=e165] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/actions/caches
                        - generic:
                          - img
                        - generic [ref=e166]: Caches
        - generic [ref=e169]:
          - generic [ref=e170]:
            - generic [ref=e171]:
              - heading "All workflows" [level=2] [ref=e173]:
                - generic [ref=e175]: All workflows
              - search [ref=e179]:
                - combobox "Filter workflow runs" [ref=e180]
                - img
            - generic [ref=e181]: Showing runs from all workflows
          - generic [ref=e182]:
            - generic [ref=e183]:
              - strong [ref=e186]: 20 workflow runs
              - generic [ref=e187]:
                - button "Workflow" [ref=e191] [cursor=pointer]:
                  - generic [ref=e193]: Workflow
                  - generic:
                    - img
                - button "Event" [ref=e197] [cursor=pointer]:
                  - generic [ref=e199]: Event
                  - generic:
                    - img
                - button "Status" [ref=e203] [cursor=pointer]:
                  - generic [ref=e205]: Status
                  - generic:
                    - img
                - button "Branch" [ref=e209] [cursor=pointer]:
                  - generic [ref=e211]: Branch
                  - generic:
                    - img
                - button "Actor" [ref=e215] [cursor=pointer]:
                  - generic [ref=e217]: Actor
                  - generic:
                    - img
            - generic [ref=e218]:
              - generic [ref=e220]:
                - generic [ref=e221]:
                  - 'link "currently running: Run 20 of CI. ci: fix test failures and timeout for CI mock mode" [ref=e222] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25602468657
                    - img "currently running:" [ref=e225]
                    - generic [ref=e229]: "ci: fix test failures and timeout for CI mock mode"
                  - generic [ref=e230]:
                    - text: "CI #20:"
                    - generic [ref=e231]:
                      - text: Commit
                      - link "1c4e71b" [ref=e232] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/commit/1c4e71bb98e6aea9aee5026dea2d63478051edee
                      - text: pushed by
                      - link "xujian519" [ref=e233] [cursor=pointer]:
                        - /url: /xujian519
                - link "main" [ref=e235] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/main
                - generic [ref=e237]:
                  - generic [ref=e238]:
                    - generic [ref=e239]:
                      - img [ref=e241]
                      - generic "May 9, 2026, 9:37 PM GMT+8" [ref=e243]: 10 minutes ago
                    - generic [ref=e244]:
                      - img [ref=e245]
                      - text: In progress
                  - group [ref=e248]:
                    - generic "Show options" [ref=e249] [cursor=pointer]:
                      - img "Show options" [ref=e250]
              - generic [ref=e253]:
                - generic [ref=e254]:
                  - 'link "failed: Run 19 of CI. style: prettier format + fix no-var-requires lint error" [ref=e255] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25602047268
                    - img "failed:" [ref=e257]
                    - generic [ref=e259]: "style: prettier format + fix no-var-requires lint error"
                  - generic [ref=e260]:
                    - text: "CI #19:"
                    - generic [ref=e261]:
                      - text: Commit
                      - link "5aa037e" [ref=e262] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/commit/5aa037e71de5cc48a2ccdacd2985bdc49e7687b1
                      - text: pushed by
                      - link "xujian519" [ref=e263] [cursor=pointer]:
                        - /url: /xujian519
                - link "main" [ref=e265] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/main
                - generic [ref=e267]:
                  - generic [ref=e268]:
                    - generic [ref=e269]:
                      - img [ref=e271]
                      - generic "May 9, 2026, 9:15 PM GMT+8" [ref=e273]: 32 minutes ago
                    - generic [ref=e274]:
                      - img "Run duration" [ref=e275]
                      - text: 4m 50s
                  - group [ref=e278]:
                    - generic "Show options" [ref=e279] [cursor=pointer]:
                      - img "Show options" [ref=e280]
              - generic [ref=e283]:
                - generic [ref=e284]:
                  - 'link "failed: Run 18 of CI. feat: Phase 2.4-3.6 — tool adaptation, execution engine, patent coord…" [ref=e285] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25601791030
                    - img "failed:" [ref=e287]
                    - generic [ref=e289]: "feat: Phase 2.4-3.6 — tool adaptation, execution engine, patent coord…"
                  - generic [ref=e290]:
                    - text: "CI #18:"
                    - generic [ref=e291]:
                      - text: Commit
                      - link "610f578" [ref=e292] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/commit/610f578b43f17ee2e1cc09f5bf90027a9ef3a408
                      - text: pushed by
                      - link "xujian519" [ref=e293] [cursor=pointer]:
                        - /url: /xujian519
                - link "main" [ref=e295] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/main
                - generic [ref=e297]:
                  - generic [ref=e298]:
                    - generic [ref=e299]:
                      - img [ref=e301]
                      - generic "May 9, 2026, 9:02 PM GMT+8" [ref=e303]: 45 minutes ago
                    - generic [ref=e304]:
                      - img "Run duration" [ref=e305]
                      - text: 4m 48s
                  - group [ref=e308]:
                    - generic "Show options" [ref=e309] [cursor=pointer]:
                      - img "Show options" [ref=e310]
              - generic [ref=e313]:
                - generic [ref=e314]:
                  - 'link "failed: Run 17 of CI. style: cargo fmt + prettier — 修复 CI 格式检查" [ref=e315] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25601115361
                    - img "failed:" [ref=e317]
                    - generic [ref=e319]: "style: cargo fmt + prettier — 修复 CI 格式检查"
                  - generic [ref=e320]:
                    - text: "CI #17:"
                    - generic [ref=e321]:
                      - text: Commit
                      - link "8465d46" [ref=e322] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/commit/8465d46add23a2e8ab30e160efa9bc619939f57b
                      - text: pushed by
                      - link "xujian519" [ref=e323] [cursor=pointer]:
                        - /url: /xujian519
                - link "main" [ref=e325] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/main
                - generic [ref=e327]:
                  - generic [ref=e328]:
                    - generic [ref=e329]:
                      - img [ref=e331]
                      - generic "May 9, 2026, 8:27 PM GMT+8" [ref=e333]: Today at 8:27 PM
                    - generic [ref=e334]:
                      - img "Run duration" [ref=e335]
                      - text: 2m 57s
                  - group [ref=e338]:
                    - generic "Show options" [ref=e339] [cursor=pointer]:
                      - img "Show options" [ref=e340]
              - generic [ref=e343]:
                - generic [ref=e344]:
                  - 'link "failed: Run 16 of CI. refactor: 代码质量审查修复 — 消除重复、修复 P0 缺陷、清理死代码" [ref=e345] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25601075652
                    - img "failed:" [ref=e347]
                    - generic [ref=e349]: "refactor: 代码质量审查修复 — 消除重复、修复 P0 缺陷、清理死代码"
                  - generic [ref=e350]:
                    - text: "CI #16:"
                    - generic [ref=e351]:
                      - text: Commit
                      - link "81bdb48" [ref=e352] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/commit/81bdb48c5444ff572afc0a991cf35f4ffbb521be
                      - text: pushed by
                      - link "xujian519" [ref=e353] [cursor=pointer]:
                        - /url: /xujian519
                - link "main" [ref=e355] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/main
                - generic [ref=e357]:
                  - generic [ref=e358]:
                    - generic [ref=e359]:
                      - img [ref=e361]
                      - generic "May 9, 2026, 8:25 PM GMT+8" [ref=e363]: Today at 8:25 PM
                    - generic [ref=e364]:
                      - img "Run duration" [ref=e365]
                      - text: 1m 24s
                  - group [ref=e368]:
                    - generic "Show options" [ref=e369] [cursor=pointer]:
                      - img "Show options" [ref=e370]
              - generic [ref=e373]:
                - generic [ref=e374]:
                  - 'link "completed successfully: Run 15 of CI. Merge pull request #1 from xujian519/feat/phase2-deep-fusion" [ref=e375] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25600410761
                    - img "completed successfully:" [ref=e377]
                    - generic [ref=e379]: "Merge pull request #1 from xujian519/feat/phase2-deep-fusion"
                  - generic [ref=e380]:
                    - text: "CI #15:"
                    - generic [ref=e381]:
                      - text: Commit
                      - link "55fc5a5" [ref=e382] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/commit/55fc5a58ff7bcea09f2278232e4012ba5507ee4e
                      - text: pushed by
                      - link "xujian519" [ref=e383] [cursor=pointer]:
                        - /url: /xujian519
                - link "main" [ref=e385] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/main
                - generic [ref=e387]:
                  - generic [ref=e388]:
                    - generic [ref=e389]:
                      - img [ref=e391]
                      - generic "May 9, 2026, 7:49 PM GMT+8" [ref=e393]: Today at 7:49 PM
                    - generic [ref=e394]:
                      - img "Run duration" [ref=e395]
                      - text: 19m 6s
                  - group [ref=e398]:
                    - generic "Show options" [ref=e399] [cursor=pointer]:
                      - img "Show options" [ref=e400]
              - generic [ref=e403]:
                - generic [ref=e404]:
                  - 'link "completed successfully: Run 14 of CI. feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪" [ref=e405] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25600124021
                    - img "completed successfully:" [ref=e407]
                    - generic [ref=e409]: "feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪"
                  - generic [ref=e410]:
                    - text: "CI #14:"
                    - generic [ref=e411]:
                      - text: Pull request
                      - link "#1" [ref=e412] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/pull/1
                      - text: synchronize by
                      - link "xujian519" [ref=e413] [cursor=pointer]:
                        - /url: /xujian519
                - link "feat/phase2-deep-fusion" [ref=e415] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/feat/phase2-deep-fusion
                - generic [ref=e417]:
                  - generic [ref=e418]:
                    - generic [ref=e419]:
                      - img [ref=e421]
                      - generic "May 9, 2026, 7:34 PM GMT+8" [ref=e423]: Today at 7:34 PM
                    - generic [ref=e424]:
                      - img "Run duration" [ref=e425]
                      - text: 19m 5s
                  - group [ref=e428]:
                    - generic "Show options" [ref=e429] [cursor=pointer]:
                      - img "Show options" [ref=e430]
              - generic [ref=e433]:
                - generic [ref=e434]:
                  - 'link "failed: Run 13 of CI. feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪" [ref=e435] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25599945009
                    - img "failed:" [ref=e437]
                    - generic [ref=e439]: "feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪"
                  - generic [ref=e440]:
                    - text: "CI #13:"
                    - generic [ref=e441]:
                      - text: Pull request
                      - link "#1" [ref=e442] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/pull/1
                      - text: synchronize by
                      - link "xujian519" [ref=e443] [cursor=pointer]:
                        - /url: /xujian519
                - link "feat/phase2-deep-fusion" [ref=e445] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/feat/phase2-deep-fusion
                - generic [ref=e447]:
                  - generic [ref=e448]:
                    - generic [ref=e449]:
                      - img [ref=e451]
                      - generic "May 9, 2026, 7:24 PM GMT+8" [ref=e453]: Today at 7:24 PM
                    - generic [ref=e454]:
                      - img "Run duration" [ref=e455]
                      - text: 8m 44s
                  - group [ref=e458]:
                    - generic "Show options" [ref=e459] [cursor=pointer]:
                      - img "Show options" [ref=e460]
              - generic [ref=e463]:
                - generic [ref=e464]:
                  - 'link "failed: Run 12 of CI. feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪" [ref=e465] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25599861676
                    - img "failed:" [ref=e467]
                    - generic [ref=e469]: "feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪"
                  - generic [ref=e470]:
                    - text: "CI #12:"
                    - generic [ref=e471]:
                      - text: Pull request
                      - link "#1" [ref=e472] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/pull/1
                      - text: synchronize by
                      - link "xujian519" [ref=e473] [cursor=pointer]:
                        - /url: /xujian519
                - link "feat/phase2-deep-fusion" [ref=e475] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/feat/phase2-deep-fusion
                - generic [ref=e477]:
                  - generic [ref=e478]:
                    - generic [ref=e479]:
                      - img [ref=e481]
                      - generic "May 9, 2026, 7:20 PM GMT+8" [ref=e483]: Today at 7:20 PM
                    - generic [ref=e484]:
                      - img "Run duration" [ref=e485]
                      - text: 3m 28s
                  - group [ref=e488]:
                    - generic "Show options" [ref=e489] [cursor=pointer]:
                      - img "Show options" [ref=e490]
              - generic [ref=e493]:
                - generic [ref=e494]:
                  - 'link "failed: Run 11 of CI. feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪" [ref=e495] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25599792132
                    - img "failed:" [ref=e497]
                    - generic [ref=e499]: "feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪"
                  - generic [ref=e500]:
                    - text: "CI #11:"
                    - generic [ref=e501]:
                      - text: Pull request
                      - link "#1" [ref=e502] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/pull/1
                      - text: synchronize by
                      - link "xujian519" [ref=e503] [cursor=pointer]:
                        - /url: /xujian519
                - link "feat/phase2-deep-fusion" [ref=e505] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/feat/phase2-deep-fusion
                - generic [ref=e507]:
                  - generic [ref=e508]:
                    - generic [ref=e509]:
                      - img [ref=e511]
                      - generic "May 9, 2026, 7:16 PM GMT+8" [ref=e513]: Today at 7:16 PM
                    - generic [ref=e514]:
                      - img "Run duration" [ref=e515]
                      - text: 3m 1s
                  - group [ref=e518]:
                    - generic "Show options" [ref=e519] [cursor=pointer]:
                      - img "Show options" [ref=e520]
              - generic [ref=e523]:
                - generic [ref=e524]:
                  - 'link "failed: Run 10 of CI. feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪" [ref=e525] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25599710178
                    - img "failed:" [ref=e527]
                    - generic [ref=e529]: "feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪"
                  - generic [ref=e530]:
                    - text: "CI #10:"
                    - generic [ref=e531]:
                      - text: Pull request
                      - link "#1" [ref=e532] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/pull/1
                      - text: synchronize by
                      - link "xujian519" [ref=e533] [cursor=pointer]:
                        - /url: /xujian519
                - link "feat/phase2-deep-fusion" [ref=e535] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/feat/phase2-deep-fusion
                - generic [ref=e537]:
                  - generic [ref=e538]:
                    - generic [ref=e539]:
                      - img [ref=e541]
                      - generic "May 9, 2026, 7:12 PM GMT+8" [ref=e543]: Today at 7:12 PM
                    - generic [ref=e544]:
                      - img "Run duration" [ref=e545]
                      - text: 3m 5s
                  - group [ref=e548]:
                    - generic "Show options" [ref=e549] [cursor=pointer]:
                      - img "Show options" [ref=e550]
              - generic [ref=e553]:
                - generic [ref=e554]:
                  - 'link "failed: Run 9 of CI. feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪" [ref=e555] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25599624865
                    - img "failed:" [ref=e557]
                    - generic [ref=e559]: "feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪"
                  - generic [ref=e560]:
                    - text: "CI #9:"
                    - generic [ref=e561]:
                      - text: Pull request
                      - link "#1" [ref=e562] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/pull/1
                      - text: synchronize by
                      - link "xujian519" [ref=e563] [cursor=pointer]:
                        - /url: /xujian519
                - link "feat/phase2-deep-fusion" [ref=e565] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/feat/phase2-deep-fusion
                - generic [ref=e567]:
                  - generic [ref=e568]:
                    - generic [ref=e569]:
                      - img [ref=e571]
                      - generic "May 9, 2026, 7:07 PM GMT+8" [ref=e573]: Today at 7:07 PM
                    - generic [ref=e574]:
                      - img "Run duration" [ref=e575]
                      - text: 3m 0s
                  - group [ref=e578]:
                    - generic "Show options" [ref=e579] [cursor=pointer]:
                      - img "Show options" [ref=e580]
              - generic [ref=e583]:
                - generic [ref=e584]:
                  - 'link "failed: Run 8 of CI. feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪" [ref=e585] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25599562162
                    - img "failed:" [ref=e587]
                    - generic [ref=e589]: "feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪"
                  - generic [ref=e590]:
                    - text: "CI #8:"
                    - generic [ref=e591]:
                      - text: Pull request
                      - link "#1" [ref=e592] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/pull/1
                      - text: synchronize by
                      - link "xujian519" [ref=e593] [cursor=pointer]:
                        - /url: /xujian519
                - link "feat/phase2-deep-fusion" [ref=e595] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/feat/phase2-deep-fusion
                - generic [ref=e597]:
                  - generic [ref=e598]:
                    - generic [ref=e599]:
                      - img [ref=e601]
                      - generic "May 9, 2026, 7:04 PM GMT+8" [ref=e603]: Today at 7:04 PM
                    - generic [ref=e604]:
                      - img "Run duration" [ref=e605]
                      - text: 2m 2s
                  - group [ref=e608]:
                    - generic "Show options" [ref=e609] [cursor=pointer]:
                      - img "Show options" [ref=e610]
              - generic [ref=e613]:
                - generic [ref=e614]:
                  - 'link "failed: Run 7 of CI. feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪" [ref=e615] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25599500834
                    - img "failed:" [ref=e617]
                    - generic [ref=e619]: "feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪"
                  - generic [ref=e620]:
                    - text: "CI #7:"
                    - generic [ref=e621]:
                      - text: Pull request
                      - link "#1" [ref=e622] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/pull/1
                      - text: synchronize by
                      - link "xujian519" [ref=e623] [cursor=pointer]:
                        - /url: /xujian519
                - link "feat/phase2-deep-fusion" [ref=e625] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/feat/phase2-deep-fusion
                - generic [ref=e627]:
                  - generic [ref=e628]:
                    - generic [ref=e629]:
                      - img [ref=e631]
                      - generic "May 9, 2026, 7:01 PM GMT+8" [ref=e633]: Today at 7:01 PM
                    - generic [ref=e634]:
                      - img "Run duration" [ref=e635]
                      - text: 1m 23s
                  - group [ref=e638]:
                    - generic "Show options" [ref=e639] [cursor=pointer]:
                      - img "Show options" [ref=e640]
              - generic [ref=e643]:
                - generic [ref=e644]:
                  - 'link "failed: Run 6 of CI. feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪" [ref=e645] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25599409314
                    - img "failed:" [ref=e647]
                    - generic [ref=e649]: "feat: Phase 2 深度融合 — 宪法引擎/Hook协议/MCP适配/CI就绪"
                  - generic [ref=e650]:
                    - text: "CI #6:"
                    - generic [ref=e651]:
                      - text: Pull request
                      - link "#1" [ref=e652] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/pull/1
                      - text: opened by
                      - link "xujian519" [ref=e653] [cursor=pointer]:
                        - /url: /xujian519
                - link "feat/phase2-deep-fusion" [ref=e655] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/feat/phase2-deep-fusion
                - generic [ref=e657]:
                  - generic [ref=e658]:
                    - generic [ref=e659]:
                      - img [ref=e661]
                      - generic "May 9, 2026, 6:56 PM GMT+8" [ref=e663]: Today at 6:56 PM
                    - generic [ref=e664]:
                      - img "Run duration" [ref=e665]
                      - text: 38s
                  - group [ref=e668]:
                    - generic "Show options" [ref=e669] [cursor=pointer]:
                      - img "Show options" [ref=e670]
              - generic [ref=e673]:
                - generic [ref=e674]:
                  - 'link "failed: Run 5 of CI. feat: 意图确认优先交互协议 + ProjectScanTool 工作目录扫描" [ref=e675] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25593474639
                    - img "failed:" [ref=e677]
                    - generic [ref=e679]: "feat: 意图确认优先交互协议 + ProjectScanTool 工作目录扫描"
                  - generic [ref=e680]:
                    - text: "CI #5:"
                    - generic [ref=e681]:
                      - text: Commit
                      - link "4aeeeb9" [ref=e682] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/commit/4aeeeb94e2c0cb8cf99880245c71a715c60306fb
                      - text: pushed by
                      - link "xujian519" [ref=e683] [cursor=pointer]:
                        - /url: /xujian519
                - link "main" [ref=e685] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/main
                - generic [ref=e687]:
                  - generic [ref=e688]:
                    - generic [ref=e689]:
                      - img [ref=e691]
                      - generic "May 9, 2026, 1:56 PM GMT+8" [ref=e693]: Today at 1:56 PM
                    - generic [ref=e694]:
                      - img "Run duration" [ref=e695]
                      - text: 53s
                  - group [ref=e698]:
                    - generic "Show options" [ref=e699] [cursor=pointer]:
                      - img "Show options" [ref=e700]
              - generic [ref=e703]:
                - generic [ref=e704]:
                  - 'link "failed: Run 4 of CI. fix: 修复4个既有测试隔离问题，同步更新规划文档" [ref=e705] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25586482554
                    - img "failed:" [ref=e707]
                    - generic [ref=e709]: "fix: 修复4个既有测试隔离问题，同步更新规划文档"
                  - generic [ref=e710]:
                    - text: "CI #4:"
                    - generic [ref=e711]:
                      - text: Commit
                      - link "5727b1d" [ref=e712] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/commit/5727b1d6f9de4162ac123c1bcbf169ae0a9b8ae5
                      - text: pushed by
                      - link "xujian519" [ref=e713] [cursor=pointer]:
                        - /url: /xujian519
                - link "main" [ref=e715] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/main
                - generic [ref=e717]:
                  - generic [ref=e718]:
                    - generic [ref=e719]:
                      - img [ref=e721]
                      - generic "May 9, 2026, 8:37 AM GMT+8" [ref=e723]: Today at 8:37 AM
                    - generic [ref=e724]:
                      - img "Run duration" [ref=e725]
                      - text: 55s
                  - group [ref=e728]:
                    - generic "Show options" [ref=e729] [cursor=pointer]:
                      - img "Show options" [ref=e730]
              - generic [ref=e733]:
                - generic [ref=e734]:
                  - 'link "failed: Run 3 of CI. 📚 docs: 添加项目规划文档（深度分析、架构图、路线图）" [ref=e735] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25554077088
                    - img "failed:" [ref=e737]
                    - generic [ref=e739]: "📚 docs: 添加项目规划文档（深度分析、架构图、路线图）"
                  - generic [ref=e740]:
                    - text: "CI #3:"
                    - generic [ref=e741]:
                      - text: Commit
                      - link "d69af6e" [ref=e742] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/commit/d69af6e560fb494930a15824e7ee6cccf840d7cb
                      - text: pushed by
                      - link "xujian519" [ref=e743] [cursor=pointer]:
                        - /url: /xujian519
                - link "main" [ref=e745] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/main
                - generic [ref=e747]:
                  - generic [ref=e748]:
                    - generic [ref=e749]:
                      - img [ref=e751]
                      - generic "May 8, 2026, 7:52 PM GMT+8" [ref=e753]: May 8, 7:52 PM GMT+8
                    - generic [ref=e754]:
                      - img "Run duration" [ref=e755]
                      - text: 3m 5s
                  - group [ref=e758]:
                    - generic "Show options" [ref=e759] [cursor=pointer]:
                      - img "Show options" [ref=e760]
              - generic [ref=e763]:
                - generic [ref=e764]:
                  - 'link "failed: Run 2 of CI. 🔧 chore: 更新.gitignore排除知识库和构建产物" [ref=e765] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25553647446
                    - img "failed:" [ref=e767]
                    - generic [ref=e769]: "🔧 chore: 更新.gitignore排除知识库和构建产物"
                  - generic [ref=e770]:
                    - text: "CI #2:"
                    - generic [ref=e771]:
                      - text: Commit
                      - link "c5c284c" [ref=e772] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/commit/c5c284cddf34a3419707ab0a0b30dfb939484e69
                      - text: pushed by
                      - link "xujian519" [ref=e773] [cursor=pointer]:
                        - /url: /xujian519
                - link "main" [ref=e775] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/main
                - generic [ref=e777]:
                  - generic [ref=e778]:
                    - generic [ref=e779]:
                      - img [ref=e781]
                      - generic "May 8, 2026, 7:41 PM GMT+8" [ref=e783]: May 8, 7:41 PM GMT+8
                    - generic [ref=e784]:
                      - img "Run duration" [ref=e785]
                      - text: 2m 52s
                  - group [ref=e788]:
                    - generic "Show options" [ref=e789] [cursor=pointer]:
                      - img "Show options" [ref=e790]
              - generic [ref=e793]:
                - generic [ref=e794]:
                  - 'link "failed: Run 1 of CI. 🧹 chore: 移除不应提交的文件" [ref=e795] [cursor=pointer]':
                    - /url: /xujian519/yunpat-agent/actions/runs/25553603345
                    - img "failed:" [ref=e797]
                    - generic [ref=e799]: "🧹 chore: 移除不应提交的文件"
                  - generic [ref=e800]:
                    - text: "CI #1:"
                    - generic [ref=e801]:
                      - text: Commit
                      - link "33cf3ca" [ref=e802] [cursor=pointer]:
                        - /url: /xujian519/yunpat-agent/commit/33cf3caffc57772a2a992576fa18997030b10167
                      - text: pushed by
                      - link "xujian519" [ref=e803] [cursor=pointer]:
                        - /url: /xujian519
                - link "main" [ref=e805] [cursor=pointer]:
                  - /url: /xujian519/yunpat-agent/tree/refs/heads/main
                - generic [ref=e807]:
                  - generic [ref=e808]:
                    - generic [ref=e809]:
                      - img [ref=e811]
                      - generic "May 8, 2026, 7:40 PM GMT+8" [ref=e813]: May 8, 7:40 PM GMT+8
                    - generic [ref=e814]:
                      - img "Run duration" [ref=e815]
                      - text: 3m 3s
                  - group [ref=e818]:
                    - generic "Show options" [ref=e819] [cursor=pointer]:
                      - img "Show options" [ref=e820]