# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tools_pb2 as tools__pb2


class PythonToolsServiceStub(object):
    """工具调用服务（Python 工具容器）
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTool = channel.unary_unary(
                '/yunpat.tools.PythonToolsService/ExecuteTool',
                request_serializer=tools__pb2.ExecuteToolRequest.SerializeToString,
                response_deserializer=tools__pb2.ExecuteToolResponse.FromString,
                )
        self.ExecuteTools = channel.unary_unary(
                '/yunpat.tools.PythonToolsService/ExecuteTools',
                request_serializer=tools__pb2.ExecuteToolsRequest.SerializeToString,
                response_deserializer=tools__pb2.ExecuteToolsResponse.FromString,
                )
        self.ListTools = channel.unary_unary(
                '/yunpat.tools.PythonToolsService/ListTools',
                request_serializer=tools__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=tools__pb2.ListToolsResponse.FromString,
                )
        self.GetToolInfo = channel.unary_unary(
                '/yunpat.tools.PythonToolsService/GetToolInfo',
                request_serializer=tools__pb2.GetToolInfoRequest.SerializeToString,
                response_deserializer=tools__pb2.GetToolInfoResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/yunpat.tools.PythonToolsService/HealthCheck',
                request_serializer=tools__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=tools__pb2.HealthCheckResponse.FromString,
                )


class PythonToolsServiceServicer(object):
    """工具调用服务（Python 工具容器）
    """

    def ExecuteTool(self, request, context):
        """执行工具
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTools(self, request, context):
        """批量执行工具
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """列出可用工具
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToolInfo(self, request, context):
        """获取工具信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PythonToolsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=tools__pb2.ExecuteToolRequest.FromString,
                    response_serializer=tools__pb2.ExecuteToolResponse.SerializeToString,
            ),
            'ExecuteTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTools,
                    request_deserializer=tools__pb2.ExecuteToolsRequest.FromString,
                    response_serializer=tools__pb2.ExecuteToolsResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=tools__pb2.ListToolsRequest.FromString,
                    response_serializer=tools__pb2.ListToolsResponse.SerializeToString,
            ),
            'GetToolInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToolInfo,
                    request_deserializer=tools__pb2.GetToolInfoRequest.FromString,
                    response_serializer=tools__pb2.GetToolInfoResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=tools__pb2.HealthCheckRequest.FromString,
                    response_serializer=tools__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yunpat.tools.PythonToolsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PythonToolsService(object):
    """工具调用服务（Python 工具容器）
    """

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yunpat.tools.PythonToolsService/ExecuteTool',
            tools__pb2.ExecuteToolRequest.SerializeToString,
            tools__pb2.ExecuteToolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yunpat.tools.PythonToolsService/ExecuteTools',
            tools__pb2.ExecuteToolsRequest.SerializeToString,
            tools__pb2.ExecuteToolsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yunpat.tools.PythonToolsService/ListTools',
            tools__pb2.ListToolsRequest.SerializeToString,
            tools__pb2.ListToolsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetToolInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yunpat.tools.PythonToolsService/GetToolInfo',
            tools__pb2.GetToolInfoRequest.SerializeToString,
            tools__pb2.GetToolInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yunpat.tools.PythonToolsService/HealthCheck',
            tools__pb2.HealthCheckRequest.SerializeToString,
            tools__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
