/**
 * PatentIntentConfig - 专利领域意图配置
 *
 * 将所有专利业务知识集中在此配置文件中，
 * 使 IntentRecognizer 的 System Prompt 保持领域无关。
 */

import type { IntentDomainConfig, IntentRecognitionResult, TaskPlan } from '../types/index.js'

/**
 * 默认的专利领域意图配置
 */
export const PatentIntentConfig: IntentDomainConfig = {
  domainName: '专利管理',
  domainDescription: '专利代理AI助手，支持专利撰写、审查答复、检索分析等任务',

  categories: [
    {
      intentId: 'DRAFT_FULL',
      label: '完整专利撰写',
      description: '用户要求撰写完整的专利申请文件',
      keywords: [
        '撰写专利',
        '写专利',
        '专利撰写',
        '专利申请',
        '写一份专利',
        '新申请',
        '申请专利',
        '起草专利',
        '编制专利',
        '准备专利申请',
        '全套申请文件',
        'draft patent',
        'write patent',
        'patent application',
        'new patent',
        'prepare patent',
        'file patent',
      ],
      complexity: 'complex',
    },
    {
      intentId: 'DRAFT_CLAIMS',
      label: '仅撰写/修改权利要求',
      description: '明确提到权利要求相关的撰写或修改',
      keywords: [
        '权利要求',
        '权要',
        'Claims',
        'claim',
        '保护范围',
        '独立权利要求',
        '从属权利要求',
        '权项',
        '修改权利要求',
        '增加从属',
        'only claims',
      ],
      complexity: 'simple',
    },
    {
      intentId: 'DRAFT_SPEC',
      label: '仅撰写说明书',
      description: '明确提到说明书相关的撰写',
      keywords: [
        '说明书',
        '具体实施方式',
        '背景技术',
        '技术领域',
        '发明内容',
        '写说明书',
        '撰写说明书',
        '生成说明书',
        'specification',
        'embodiment',
        'only specification',
      ],
      complexity: 'simple',
    },
    {
      intentId: 'RESPOND_OA',
      label: '审查意见答复',
      description: '提到审查意见或答复相关的需求',
      keywords: [
        '审查意见',
        'OA',
        'office action',
        '答复审查',
        '审查意见答复',
        'oa答复',
        '审查员',
        '驳回',
        '第一次审查意见',
        '第二次审查意见',
        '一通',
        '二通',
        '答复期限',
        '创造性',
        '新颖性',
        '实用性',
        '修改权利要求',
        '意见陈述书',
        '审查通知书',
        '驳回决定',
        '答辩',
        '申述',
        'respond to office action',
        'official action',
        'examination opinion',
      ],
      complexity: 'complex',
    },
    {
      intentId: 'SEARCH',
      label: '现有技术检索',
      description: '明确要求检索或查找相关技术',
      keywords: [
        '检索',
        '搜索',
        '查新',
        '现有技术',
        '相关技术',
        '查一下',
        '搜索专利',
        '有没有类似的',
        '对比文件',
        '专利检索',
        'prior art',
        'patent search',
        'lookup',
        '查找',
        '查询',
        '专利号',
        '申请号',
        '新颖性检索',
        '可专利性检索',
      ],
      complexity: 'simple',
    },
    {
      intentId: 'ANALYZE_PORTFOLIO',
      label: '专利组合分析',
      description: '分析多个专利的组合情况',
      keywords: [
        '专利组合',
        '专利分析',
        '技术布局',
        '专利地图',
        'FTO',
        '自由实施',
        '侵权分析',
        '侵权判定',
        '技术特征对比',
        '侵权风险',
        '被控侵权',
        '创新评估',
        '可专利性评估',
        '创新性',
        '商标分析',
        '商标注册',
      ],
      complexity: 'complex',
    },
    {
      intentId: 'EVALUATE_INNOVATION',
      label: '创新性评估',
      description: '评估发明的创新性水平，判断是否值得申请专利',
      keywords: ['创新评估', '是否值得申请', '创新性', '可专利性评估', '评级', 'A/B/C/D'],
      complexity: 'complex',
    },
    {
      intentId: 'ANALYZE_INFRINGEMENT',
      label: '专利侵权分析',
      description: '分析专利侵权的可能性，包括技术特征对比和风险评级',
      keywords: ['侵权分析', '侵权判定', '全面覆盖', '等同侵权', '技术特征对比', '被控侵权'],
      complexity: 'complex',
    },
    {
      intentId: 'ANALYZE_TRADEMARK',
      label: '商标分析',
      description: '商标可注册性评估、近似判断、驳回复审策略',
      keywords: ['商标分析', '商标注册', '近似判断', '显著性分析', '驳回复审', '商标异议'],
      complexity: 'simple',
    },
    {
      intentId: 'CODING',
      label: '编程开发任务',
      description: '用户要求写代码、开发功能、调试程序等编程相关任务',
      keywords: [
        '写代码',
        '编程',
        '开发',
        '写个函数',
        '调试',
        '实现',
        '接口',
        'bug',
        '部署',
        'function',
        'programming',
        'coding',
        'write code',
        'implement',
        'debug',
      ],
      complexity: 'simple',
    },
    {
      intentId: 'MULTI_INTENT',
      label: '多意图',
      description: '一条消息包含多个不同的任务需求',
      keywords: [],
      complexity: 'complex',
      isSystemIntent: true,
    },
    {
      intentId: 'CLARIFY',
      label: '需要追问',
      description: '意图不明确，信息不足以确定具体任务',
      keywords: [],
      complexity: 'simple',
      isSystemIntent: true,
    },
    {
      intentId: 'INIT_WORKSPACE',
      label: '工作区初始化',
      description: '扫描工作区目录，检测专利相关文件并推断任务意图',
      keywords: ['初始化', '扫描', '工作区', '目录'],
      complexity: 'simple',
      isSystemIntent: true,
    },
  ],

  fewShotExamples: [
    {
      input: '帮我撰写一个关于智能控制器的专利申请',
      output: {
        intent: 'DRAFT_FULL',
        confidence: 0.95,
        complexity: 'complex',
        extracted: {
          title: '智能控制器',
          field: '控制技术',
          hasAttachment: false,
          urgency: 'normal',
          keywords: ['智能控制器', '撰写', '专利申请'],
        },
      } as IntentRecognitionResult,
    },
    {
      input: '帮我修改权利要求，增加从属权利要求',
      output: {
        intent: 'DRAFT_CLAIMS',
        confidence: 0.92,
        complexity: 'simple',
        extracted: {
          title: '',
          field: '',
          hasAttachment: false,
          urgency: 'normal',
          keywords: ['权利要求', '从属权利要求', '修改'],
        },
      } as IntentRecognitionResult,
    },
    {
      input: '只写说明书部分，不要权利要求',
      output: {
        intent: 'DRAFT_SPEC',
        confidence: 0.9,
        complexity: 'simple',
        extracted: {
          title: '',
          field: '',
          hasAttachment: false,
          urgency: 'normal',
          keywords: ['说明书', '不要权利要求'],
        },
      } as IntentRecognitionResult,
    },
    {
      input: '我收到了审查意见，需要帮忙答复',
      output: {
        intent: 'CLARIFY',
        confidence: 0.6,
        complexity: 'complex',
        extracted: {
          hasAttachment: false,
          urgency: 'normal',
          keywords: ['审查意见', '答复'],
        },
        clarifyQuestion:
          '请问您是否已经上传了审查意见文件？如果已上传，我将自动分析审查意见并生成答复策略。',
      } as IntentRecognitionResult,
    },
    {
      input: '帮我检索一下智能控制器的现有技术',
      output: {
        intent: 'SEARCH',
        confidence: 0.93,
        complexity: 'simple',
        extracted: {
          title: '智能控制器',
          field: '控制技术',
          hasAttachment: false,
          urgency: 'normal',
          keywords: ['检索', '智能控制器', '现有技术'],
        },
      } as IntentRecognitionResult,
    },
    {
      input: '分析我们公司的专利组合情况',
      output: {
        intent: 'ANALYZE_PORTFOLIO',
        confidence: 0.88,
        complexity: 'complex',
        extracted: {
          title: '',
          field: '',
          hasAttachment: false,
          urgency: 'normal',
          keywords: ['专利组合', '分析', '公司'],
        },
      } as IntentRecognitionResult,
    },
    {
      input: '帮我写一个 PDF 解析函数',
      output: {
        intent: 'CODING',
        confidence: 0.95,
        complexity: 'simple',
        extracted: {
          title: '',
          field: '',
          hasAttachment: false,
          urgency: 'normal',
          keywords: ['写代码', 'PDF', '解析函数'],
        },
      } as IntentRecognitionResult,
    },
    {
      input: '先帮我检索现有技术，然后撰写完整的专利申请',
      output: {
        intent: 'MULTI_INTENT',
        confidence: 0.91,
        complexity: 'complex',
        extracted: {
          title: '',
          field: '',
          hasAttachment: false,
          urgency: 'normal',
          keywords: ['检索', '撰写', '专利申请'],
        },
      } as IntentRecognitionResult,
    },
    {
      input: '这是一个关于新能源汽车的技术方案，帮我写专利',
      output: {
        intent: 'DRAFT_FULL',
        confidence: 0.94,
        complexity: 'complex',
        extracted: {
          title: '新能源汽车',
          field: '汽车技术',
          hasAttachment: true,
          urgency: 'normal',
          keywords: ['新能源汽车', '技术方案', '写专利'],
        },
      } as IntentRecognitionResult,
    },
    {
      input: '紧急！需要今天完成专利撰写',
      output: {
        intent: 'DRAFT_FULL',
        confidence: 0.89,
        complexity: 'complex',
        extracted: {
          title: '',
          field: '',
          hasAttachment: false,
          urgency: 'urgent',
          keywords: ['紧急', '今天完成', '专利撰写'],
        },
      } as IntentRecognitionResult,
    },
  ],

  /** 意图到 Agent 的直达路由映射（简单意图用） */
  directRoutes: {
    DRAFT_FULL: 'specification-drafter',
    DRAFT_CLAIMS: 'claim-generator',
    DRAFT_SPEC: 'specification-drafter',
    RESPOND_OA: 'patent-responder',
    SEARCH: 'search',
    ANALYZE_PORTFOLIO: 'patent-analyzer',
    EVALUATE_INNOVATION: 'innovation-evaluator',
    ANALYZE_INFRINGEMENT: 'patent-infringement-analyzer',
    ANALYZE_TRADEMARK: 'trademark-analyzer',
  },

  /** 默认任务计划模板（LLM 失败时的降级方案） */
  defaultPlans: {
    DRAFT_FULL: (intent: IntentRecognitionResult): TaskPlan => ({
      planId: `plan-${Date.now()}`,
      intent: 'DRAFT_FULL',
      estimatedMinutes: 45,
      steps: [
        {
          stepId: 'search-prior-art',
          agentId: 'search',
          layer: 'execution',
          parallel: true,
          dependsOn: [],
          timeout: 60000,
          input: {
            mode: 'iterative',
            query: intent.extracted.title || intent.extracted.keywords.join(' '),
            databases: ['cn_patent', 'us_patent'],
          },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 3,
        },
        {
          stepId: 'query-knowledge-base',
          agentId: 'researcher',
          layer: 'execution',
          parallel: true,
          dependsOn: [],
          timeout: 30000,
          input: {
            query: intent.extracted.title || intent.extracted.keywords.join(' '),
            domain: intent.extracted.field,
          },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 2,
        },
        {
          stepId: 'understand-invention',
          agentId: 'invention',
          layer: 'domain',
          parallel: false,
          dependsOn: ['search-prior-art', 'query-knowledge-base'],
          timeout: 60000,
          input: {
            task: 'understand-invention',
            inventionTitle: intent.extracted.title,
          },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 2,
        },
        {
          stepId: 'draft-claims',
          agentId: 'claim-generator',
          layer: 'domain',
          parallel: false,
          dependsOn: ['understand-invention'],
          timeout: 90000,
          input: { task: 'draft-claims' },
          hitl: true,
          hitlDescription: '请审阅生成的权利要求，确认保护范围和技术特征是否准确',
          retryOnFailure: true,
          maxRetries: 2,
        },
        {
          stepId: 'draft-specification',
          agentId: 'specification-drafter',
          layer: 'domain',
          parallel: false,
          dependsOn: ['draft-claims'],
          timeout: 120000,
          input: { task: 'draft-specification' },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 2,
        },
        {
          stepId: 'claims-formality-check',
          agentId: 'claim-generator',
          layer: 'execution',
          parallel: true,
          dependsOn: ['draft-claims'],
          timeout: 30000,
          input: { task: 'formality-check' },
          hitl: false,
          retryOnFailure: false,
          maxRetries: 0,
        },
        {
          stepId: 'spec-formality-check',
          agentId: 'spec-formality-checker',
          layer: 'execution',
          parallel: true,
          dependsOn: ['draft-specification'],
          timeout: 30000,
          input: {},
          hitl: false,
          retryOnFailure: false,
          maxRetries: 0,
        },
        {
          stepId: 'generate-docx',
          agentId: 'writer',
          layer: 'execution',
          parallel: false,
          dependsOn: ['draft-specification', 'claims-formality-check', 'spec-formality-check'],
          timeout: 30000,
          input: { format: 'docx', patentOfficeFormat: 'CNIPA' },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 2,
        },
      ],
      hitlCheckpoints: ['draft-claims'],
      metadata: {
        createdAt: new Date(),
        parallelizable: true,
        estimatedCost: 0.15,
      },
    }),

    RESPOND_OA: (_intent: IntentRecognitionResult): TaskPlan => ({
      planId: `plan-${Date.now()}`,
      intent: 'RESPOND_OA',
      estimatedMinutes: 60,
      steps: [
        {
          stepId: 'parse-oa',
          agentId: 'patent-responder',
          layer: 'domain',
          parallel: false,
          dependsOn: [],
          timeout: 30000,
          input: { task: 'parse-oa' },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 2,
        },
        {
          stepId: 'search-counter-evidence',
          agentId: 'search',
          layer: 'execution',
          parallel: false,
          dependsOn: ['parse-oa'],
          timeout: 60000,
          input: { mode: 'iterative', query: '反证检索' },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 3,
        },
        {
          stepId: 'determine-response-strategy',
          agentId: 'patent-responder',
          layer: 'domain',
          parallel: false,
          dependsOn: ['search-counter-evidence'],
          timeout: 60000,
          input: { task: 'determine-strategy' },
          hitl: true,
          hitlDescription: '请确认答复策略：修改权利要求、争辩、还是组合策略',
          retryOnFailure: true,
          maxRetries: 2,
        },
        {
          stepId: 'draft-response',
          agentId: 'patent-responder',
          layer: 'domain',
          parallel: false,
          dependsOn: ['determine-response-strategy'],
          timeout: 120000,
          input: { task: 'draft-response' },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 2,
        },
      ],
      hitlCheckpoints: ['determine-response-strategy'],
      metadata: {
        createdAt: new Date(),
        parallelizable: false,
        estimatedCost: 0.2,
      },
    }),

    ANALYZE_PORTFOLIO: (_intent: IntentRecognitionResult): TaskPlan => ({
      planId: `plan-${Date.now()}`,
      intent: 'ANALYZE_PORTFOLIO',
      estimatedMinutes: 30,
      steps: [
        {
          stepId: 'collect-patents',
          agentId: 'patent-analyzer',
          layer: 'domain',
          parallel: false,
          dependsOn: [],
          timeout: 30000,
          input: { task: 'collect-patents' },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 2,
        },
        {
          stepId: 'analyze-technical-distribution',
          agentId: 'patent-analyzer',
          layer: 'domain',
          parallel: false,
          dependsOn: ['collect-patents'],
          timeout: 60000,
          input: { task: 'analyze-distribution' },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 2,
        },
        {
          stepId: 'evaluate-value',
          agentId: 'patent-analyzer',
          layer: 'domain',
          parallel: false,
          dependsOn: ['analyze-technical-distribution'],
          timeout: 60000,
          input: { task: 'evaluate-value' },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 2,
        },
        {
          stepId: 'generate-report',
          agentId: 'patent-analyzer',
          layer: 'domain',
          parallel: false,
          dependsOn: ['evaluate-value'],
          timeout: 60000,
          input: { task: 'generate-report' },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 2,
        },
      ],
      hitlCheckpoints: [],
      metadata: {
        createdAt: new Date(),
        parallelizable: false,
        estimatedCost: 0.12,
      },
    }),

    MULTI_INTENT: (intent: IntentRecognitionResult): TaskPlan => ({
      planId: `plan-${Date.now()}`,
      intent: 'MULTI_INTENT',
      estimatedMinutes: 60,
      steps: [
        {
          stepId: 'task-1-search',
          agentId: 'search',
          layer: 'execution',
          parallel: true,
          dependsOn: [],
          timeout: 60000,
          input: { query: intent.extracted.keywords.join(' ') },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 3,
        },
        {
          stepId: 'task-2-draft',
          agentId: 'specification-drafter',
          layer: 'domain',
          parallel: false,
          dependsOn: ['task-1-search'],
          timeout: 120000,
          input: { task: 'draft-full' },
          hitl: true,
          hitlDescription: '请确认完整的专利申请内容',
          retryOnFailure: true,
          maxRetries: 2,
        },
      ],
      hitlCheckpoints: ['task-2-draft'],
      metadata: {
        createdAt: new Date(),
        parallelizable: true,
        estimatedCost: 0.18,
      },
    }),

    EVALUATE_INNOVATION: (intent: IntentRecognitionResult): TaskPlan => ({
      planId: `plan-evaluate-innovation-${Date.now()}`,
      intent: 'EVALUATE_INNOVATION',
      estimatedMinutes: 20,
      steps: [
        {
          stepId: 'search-prior-art',
          agentId: 'prior-art-search',
          layer: 'execution',
          parallel: false,
          dependsOn: [],
          timeout: 60000,
          input: {
            mode: 'iterative',
            query: intent.extracted.title || intent.extracted.keywords?.join(' ') || '',
          },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 2,
        },
        {
          stepId: 'evaluate-innovation',
          agentId: 'innovation-evaluator',
          layer: 'domain',
          parallel: false,
          dependsOn: ['search-prior-art'],
          timeout: 90000,
          input: {
            task: 'evaluate-innovation',
            inventionTitle: intent.extracted.title,
          },
          hitl: true,
          hitlDescription: '请审阅创新性评估结果和专利申请建议',
          retryOnFailure: true,
          maxRetries: 2,
        },
      ],
      hitlCheckpoints: ['evaluate-innovation'],
      metadata: {
        createdAt: new Date(),
        parallelizable: false,
        estimatedCost: 0.12,
      },
    }),

    ANALYZE_INFRINGEMENT: (_intent: IntentRecognitionResult): TaskPlan => ({
      planId: `plan-infringement-${Date.now()}`,
      intent: 'ANALYZE_INFRINGEMENT',
      estimatedMinutes: 30,
      steps: [
        {
          stepId: 'extract-features',
          agentId: 'tech-unit',
          layer: 'execution',
          parallel: false,
          dependsOn: [],
          timeout: 30000,
          input: { task: 'extract-features' },
          hitl: false,
          retryOnFailure: true,
          maxRetries: 2,
        },
        {
          stepId: 'analyze-infringement',
          agentId: 'patent-infringement-analyzer',
          layer: 'domain',
          parallel: false,
          dependsOn: ['extract-features'],
          timeout: 60000,
          input: { task: 'analyze-infringement' },
          hitl: true,
          hitlDescription: '请审阅侵权分析结果和风险评级',
          retryOnFailure: true,
          maxRetries: 2,
        },
      ],
      hitlCheckpoints: ['analyze-infringement'],
      metadata: {
        createdAt: new Date(),
        parallelizable: false,
        estimatedCost: 0.12,
      },
    }),

    ANALYZE_TRADEMARK: (intent: IntentRecognitionResult): TaskPlan => ({
      planId: `plan-trademark-${Date.now()}`,
      intent: 'ANALYZE_TRADEMARK',
      estimatedMinutes: 15,
      steps: [
        {
          stepId: 'analyze-trademark',
          agentId: 'trademark-analyzer',
          layer: 'domain',
          parallel: false,
          dependsOn: [],
          timeout: 45000,
          input: {
            task: 'analyze-trademark',
            trademarkName: intent.extracted.title || intent.extracted.keywords?.join(' ') || '',
          },
          hitl: true,
          hitlDescription: '请审阅商标分析结果',
          retryOnFailure: true,
          maxRetries: 2,
        },
      ],
      hitlCheckpoints: ['analyze-trademark'],
      metadata: {
        createdAt: new Date(),
        parallelizable: false,
        estimatedCost: 0.08,
      },
    }),
  },
}
