# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\ryunpat.common\"\xb5\x01\n\rErrorResponse\x12\'\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x19.yunpat.common.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12:\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32).yunpat.common.ErrorResponse.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x90\x01\n\x08Metadata\x12/\n\x04tags\x18\x01 \x03(\x0b\x32!.yunpat.common.Metadata.TagsEntry\x12\x12\n\ncreated_at\x18\x02 \x01(\x03\x12\x12\n\nupdated_at\x18\x03 \x01(\x03\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"R\n\x0bPageRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x0f\n\x07sort_by\x18\x03 \x01(\t\x12\x11\n\tascending\x18\x04 \x01(\x08\"S\n\x0cPageResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\x12\x13\n\x0btotal_pages\x18\x04 \x01(\x05*O\n\nStatusCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x12\x0b\n\x07TIMEOUT\x10\x03\x12\r\n\tCANCELLED\x10\x04*5\n\x08Priority\x12\x07\n\x03LOW\x10\x00\x12\n\n\x06MEDIUM\x10\x01\x12\x08\n\x04HIGH\x10\x02\x12\n\n\x06URGENT\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ERRORRESPONSE_DETAILSENTRY']._options = None
  _globals['_ERRORRESPONSE_DETAILSENTRY']._serialized_options = b'8\001'
  _globals['_METADATA_TAGSENTRY']._options = None
  _globals['_METADATA_TAGSENTRY']._serialized_options = b'8\001'
  _globals['_STATUSCODE']._serialized_start=531
  _globals['_STATUSCODE']._serialized_end=610
  _globals['_PRIORITY']._serialized_start=612
  _globals['_PRIORITY']._serialized_end=665
  _globals['_ERRORRESPONSE']._serialized_start=32
  _globals['_ERRORRESPONSE']._serialized_end=213
  _globals['_ERRORRESPONSE_DETAILSENTRY']._serialized_start=167
  _globals['_ERRORRESPONSE_DETAILSENTRY']._serialized_end=213
  _globals['_METADATA']._serialized_start=216
  _globals['_METADATA']._serialized_end=360
  _globals['_METADATA_TAGSENTRY']._serialized_start=317
  _globals['_METADATA_TAGSENTRY']._serialized_end=360
  _globals['_PAGEREQUEST']._serialized_start=362
  _globals['_PAGEREQUEST']._serialized_end=444
  _globals['_PAGERESPONSE']._serialized_start=446
  _globals['_PAGERESPONSE']._serialized_end=529
# @@protoc_insertion_point(module_scope)
